name: Java CI/CD With Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3: Build with Maven
      - name: Build with Maven
        working-directory: liquor-store-api  # Navigate to the folder containing pom.xml
        run: mvn clean install

      # Step 4: Run tests with Maven
      - name: Test with Maven
        working-directory: liquor-store-api  # Navigate to the folder containing pom.xml
        run: mvn test
